// Generated by Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)
#ifndef CAPTURESDK_SWIFT_H
#define CAPTURESDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreBluetooth;
@import Dispatch;
@import Foundation;
@import ObjectiveC;
#endif

#import <CaptureSDK/CaptureSDK.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="CaptureSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

/// Authentication mode
typedef SWIFT_ENUM(uint8_t, AuthenticationMode, open) {
  AuthenticationModeNone = 0x00,
  AuthenticationModeAes128 = 0x01,
};

@class NSString;
@class SKTCapture;
@protocol CaptureHelperDelegate;
@class CaptureHelperDevice;
@class CaptureHelperDeviceManager;
@class SKTAppInfo;
@class SKTCaptureEvent;
@class SKTCaptureVersion;
@class SKTCaptureProperty;

/// Main entry point for using Capture
/// 1- get a Capture instance by using CaptureHelper.sharedInstance
/// 2- push a View Controller delegate reference that is compliant to a CaptureHelperDelegate protocol
/// 3- fill a SKTAppInfo with developer ID, bundle ID and AppKey coming from Socket Mobile developer portal
/// 4- open Capture with the SKTAppInfo instance
SWIFT_CLASS("_TtC10CaptureSDK13CaptureHelper")
@interface CaptureHelper : NSObject <SKTCaptureDelegate>
/// can store any object that can be used in an extension
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull extensionProperties;
/// dispatch queue that can be set to the
/// main queue so the completion handlers
/// can update directly the UI controls
/// set this property to DispatchQueue.main
@property (nonatomic, strong) dispatch_queue_t _Nullable dispatchQueue;
/// static shared instance of CaptureHelper
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) CaptureHelper * _Nonnull sharedInstance;)
+ (CaptureHelper * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// reference to the Capture API that can be used in
/// extension class
@property (nonatomic, readonly, strong) SKTCapture * _Nullable captureApi;
/// push a delegate reference into the delegates stack
/// each new View can push its delegate reference and the
/// last one pushed is the one used for receiving the Capture
/// delegates.
/// NOTE: If a device is already connected to the host, doing a pushDelegate
/// will call the didNotifyArrivalForDevice if the delegate pushed supports
/// this in its protocol.
/// \param delegate reference to a delegate to push in the delegates stack
///
///
/// returns:
///
/// hasBeenPushed : true is the delegate has been pushed, false otherwise
- (BOOL)pushDelegate:(id <CaptureHelperDelegate> _Nonnull)delegate;
- (BOOL)popDelegate:(id <CaptureHelperDelegate> _Nonnull)delegate;
/// get the list of devices this CaptureHelper has opened
///
/// returns:
/// list of CaptureHelperDevice opened by Capture Helper
- (NSArray<CaptureHelperDevice *> * _Nonnull)getDevices SWIFT_WARN_UNUSED_RESULT;
/// get the list of device managers this CaptureHelper has opened
///
/// returns:
/// list of CaptureHelperDeviceManager opened by Capture Helper
- (NSArray<CaptureHelperDeviceManager *> * _Nonnull)getDeviceManagers SWIFT_WARN_UNUSED_RESULT;
/// open Capture
/// Main entry point of the Capture SDK. This method should be called first.
/// open Capture with the application information which contains
/// the developer ID, the application Bundle ID and the AppKey that
/// can be retrieved on the Socket Mobile developer portal
/// The delegates should be pushed before calling this method to make sure
/// none of the events are missed.
/// \param appInfo class containing developer ID, application Bundle ID and the AppKey
///
/// \param completionHandler called upon completion with the result code
///
- (void)openWithAppInfo:(SKTAppInfo * _Nonnull)appInfo withCompletionHandler:(void (^ _Nonnull)(SKTResult))completion;
/// close Capture, once this method is called the application won’t
/// receive anything from Capture
/// it closes devices and device managers
/// \param completionHandler called upon complete with the result code
///
- (void)closeWithCompletionHandler:(void (^ _Nonnull)(SKTResult))completion;
/// delegate from Capture that is called each time a Capture event is fired
/// \param event Capture event sent by Capture to the application
///
/// \param capture reference of the capture the event refers to
///
/// \param result result code of the event
///
- (void)didReceiveEvent:(SKTCaptureEvent * _Nonnull)event forCapture:(SKTCapture * _Nonnull)capture withResult:(SKTResult)result;
/// retrieve the Capture version
/// \param completion called upon completion of getting the Capture version
/// with the result and the version as argument.
///
- (void)getVersionWithCompletionHandler:(void (^ _Nonnull)(SKTResult, SKTCaptureVersion * _Nullable))completion;
/// set the confirmation mode to define how the decoded data should be confirmed.
/// \param confirmationMode confirmationMode contains the confirmation mode to set Capture with
///
/// \param completion called upon completion of setting the confirmation mode
/// with the result of setting the confirmation mode.
///
- (void)setConfirmationMode:(SKTCaptureDataConfirmation)confirmationMode withCompletionHandler:(void (^ _Nonnull)(SKTResult))completion;
/// set the SocketCam (Scanning using the host camera) status. The status could
/// be “not supported”, “supported”, “disabled” and “enabled”.
/// \param status contains the new SocketCam status
///
/// \param completion called upon completion of setting the SocketCam status with the
/// result as argument.
///
- (void)setSocketCamStatus:(SKTCaptureSocketCam)status withCompletionHandler:(void (^ _Nonnull)(SKTResult))completion;
/// get a property using the Capture property object
/// Usually the get property sends a property without arguments but
/// the response in case of success contains a property response that
/// holds the eventual arguments of the property.
/// \param property reference to the property to set
///
/// \param completion receiving the result and the device specific command response if the result is successful
///
- (void)getProperty:(SKTCaptureProperty * _Nonnull)property withCompletionHandler:(void (^ _Nonnull)(SKTResult, SKTCaptureProperty * _Nullable))completion;
/// set a property using the Capture property object
/// Usually the set property does not return any property arguments,
/// only the result is interesting to check to know if the set property
/// has been successful.
/// \param property reference to the property to set
///
/// \param completion receiving the result and the device specific command response if the result is successful
///
- (void)setProperty:(SKTCaptureProperty * _Nonnull)property withCompletionHandler:(void (^ _Nonnull)(SKTResult, SKTCaptureProperty * _Nullable))completion;
@end


/// Capture Helper base protocol does not have
/// any delegate, it could be used for View Controllers
/// that don’t require any notification from Capture
SWIFT_PROTOCOL("_TtP10CaptureSDK21CaptureHelperDelegate_")
@protocol CaptureHelperDelegate
@end


/// Capture Helper protocol to comply in order to receive the device manager arrival, removal notifications
SWIFT_PROTOCOL("_TtP10CaptureSDK42CaptureHelperDeviceManagerPresenceDelegate_")
@protocol CaptureHelperDeviceManagerPresenceDelegate <CaptureHelperDelegate>
/// delegate called when a device manager connects to the host
/// \param device contains the device manager information, such as device type
///
/// \param result contains the result of the device manager connecting to the host
///
- (void)didNotifyArrivalForDeviceManager:(CaptureHelperDeviceManager * _Nonnull)device withResult:(SKTResult)result;
/// delegate called when a device manager disconnects from the host
/// \param device contains the device manager information, such as device type
///
/// \param result contains the result of the device manager disconnecting from the host
///
- (void)didNotifyRemovalForDeviceManager:(CaptureHelperDeviceManager * _Nonnull)device withResult:(SKTResult)result;
@end


/// Capture Helper protocol to comply in order to receive the buttons state
SWIFT_PROTOCOL("_TtP10CaptureSDK34CaptureHelperDeviceButtonsDelegate_")
@protocol CaptureHelperDeviceButtonsDelegate <CaptureHelperDelegate>
/// delegate called when the state of the device’s buttons has changed
/// \param buttonsState contains the new buttons state
///
/// \param device contains the device information from which the buttons state has changed
///
- (void)didChangeButtonsState:(SKTCaptureButtonsState)buttonsState forDevice:(CaptureHelperDevice * _Nonnull)device;
@end

@class SKTCaptureDecodedData;

/// Capture Helper protocol to comply in order to receive the decoded data
SWIFT_PROTOCOL("_TtP10CaptureSDK38CaptureHelperDeviceDecodedDataDelegate_")
@protocol CaptureHelperDeviceDecodedDataDelegate <CaptureHelperDelegate>
/// delegate called when the decoded data is received from a device
/// \param decodedData contains the decoded data with its related information
///
/// \param device contains the device information from which the data has been decoded
///
/// \param result contains the result of the decoded data, most of the time it’s success
/// but in the case of SocketCam the result can be E_CANCELLED when the user cancel
/// the scan.
///
- (void)didReceiveDecodedData:(SKTCaptureDecodedData * _Nullable)decodedData fromDevice:(CaptureHelperDevice * _Nonnull)device withResult:(SKTResult)result;
@end


/// Capture Helper protocol to comply in order to receive the power and battery information
SWIFT_PROTOCOL("_TtP10CaptureSDK32CaptureHelperDevicePowerDelegate_")
@protocol CaptureHelperDevicePowerDelegate <CaptureHelperDelegate>
/// delegate called when the power state has changed, this is happening when plug in the device to a power adapter
/// \param powerState contains the new power state of the device, @see SKTCapturePowerState
///
/// \param device contains the device information for which the power state has changed
///
- (void)didChangePowerState:(SKTCapturePowerState)powerState forDevice:(CaptureHelperDevice * _Nonnull)device;
/// delegate called when the battery level has changed
/// \param batteryLevel contains the battery level in %
///
/// \param device contains the device information for which the battery level has changed
///
- (void)didChangeBatteryLevel:(NSInteger)batteryLevel forDevice:(CaptureHelperDevice * _Nonnull)device;
@end


/// Capture Helper protocol to comply in order to receive the device arrival, removal notifications
SWIFT_PROTOCOL("_TtP10CaptureSDK35CaptureHelperDevicePresenceDelegate_")
@protocol CaptureHelperDevicePresenceDelegate <CaptureHelperDelegate>
/// delegate called when a device connects to the host
/// \param device contains the device information, such as friendly name and device type
///
/// \param result contains the result of the device connecting to the host
///
- (void)didNotifyArrivalForDevice:(CaptureHelperDevice * _Nonnull)device withResult:(SKTResult)result;
/// delegate called when a device disconnects from the host
/// \param device contains the device information, such as friendly name and device type
///
/// \param result contains the result of the device disconnecting from the host
///
- (void)didNotifyRemovalForDevice:(CaptureHelperDevice * _Nonnull)device withResult:(SKTResult)result;
@end


/// Capture Helper protocol to comply in order to receive any error coming
/// from Capture
SWIFT_PROTOCOL("_TtP10CaptureSDK26CaptureHelperErrorDelegate_")
@protocol CaptureHelperErrorDelegate <CaptureHelperDelegate>
/// delegate called when an unexpected error arises
/// \param error contains the error code
///
- (void)didReceiveError:(SKTResult)error;
@end


/// Capture Helper protocol to comply in order to receive all the Capture delegates
/// use this protocol if the applications needs to handle all the notifications
/// coming from Capture
SWIFT_PROTOCOL("_TtP10CaptureSDK24CaptureHelperAllDelegate_")
@protocol CaptureHelperAllDelegate <CaptureHelperDeviceButtonsDelegate, CaptureHelperDeviceDecodedDataDelegate, CaptureHelperDeviceManagerPresenceDelegate, CaptureHelperDevicePowerDelegate, CaptureHelperDevicePresenceDelegate, CaptureHelperErrorDelegate>
@end


@class SKTCaptureDeviceInfo;
@class NSData;
@class SKTCaptureDataSource;

/// Capture Helper device, represents a device that is attached to Capture
SWIFT_CLASS("_TtC10CaptureSDK19CaptureHelperDevice")
@interface CaptureHelperDevice : NSObject
/// can store an object that can be used for extension
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull extensionProperties;
/// contains information about the device
/// such as the device friendly name and device type
@property (nonatomic, strong) SKTCaptureDeviceInfo * _Nonnull deviceInfo;
/// specify the main Dispatch queue so the UI controls
/// can be updated directly inside the completion handlers
@property (nonatomic, strong) dispatch_queue_t _Nullable dispatchQueue;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// retrieve the device friendly name
/// \param completion closure receiving the response with the result and the friendly name of
/// the device if the result is successful
///
- (void)getFriendlyNameWithCompletionHandler:(void (^ _Nonnull)(SKTResult, NSString * _Nullable))completion;
/// set the device friendly name. The device friendly name has a limit of
/// 32 UTF8 characters including the null terminated character, an error is
/// generated if the friendly name is too long.
/// \param name friendly name to set the device with
///
/// \param completion closure receiving the result of setting the new friendly name
///
- (void)setFriendlyName:(NSString * _Nonnull)name withCompletionHandler:(void (^ _Nonnull)(SKTResult))completion;
/// get the device Bluetooth address
/// \param completion receiving the result of getting the device Bluetooth Address if the result
///
- (void)getBluetoothAddressWithCompletionHandler:(void (^ _Nonnull)(SKTResult, NSData * _Nullable))completion;
/// get the device Firmware version
/// \param completion receiving the result and the device Firmware version if the result is successful
///
- (void)getFirmwareVersionWithCompletionHandler:(void (^ _Nonnull)(SKTResult, SKTCaptureVersion * _Nullable))completion;
/// set the device stand configuration
/// \param config config stand configuration to set the device with
///
/// \param completion block receiving the result of changing the device stand configuration
///
- (void)setStandConfig:(SKTCaptureStandConfig)config withCompletionHandler:(void (^ _Nonnull)(SKTResult))completion;
/// set the device decode action
/// \param decodeAction decode action to set the device with
///
/// \param completion receiving the result of changing the device decode action
///
- (void)setDecodeAction:(SKTCaptureLocalDecodeAction)decodeAction withCompletionHandler:(void (^ _Nonnull)(SKTResult))completion;
/// set the device local data acknowledgment
/// \param dataAcknowledgment set how the device acknwoledges data locally on the device
///
/// \param completion receiving the result of changing the device stand configuration
///
- (void)setDataAcknowledgment:(SKTCaptureDeviceDataAcknowledgment)dataAcknowledgment withCompletionHandler:(void (^ _Nonnull)(SKTResult))completion;
/// get the device postamble
/// \param completion receiving the result and the device postamble if the result is successful
///
- (void)getPostambleWithCompletionHandler:(void (^ _Nonnull)(SKTResult, NSString * _Nullable))completion;
/// set the device postamble
/// \param postamble postamble to set the device with
///
/// \param completion receiving the result of changing the device postamble
///
- (void)setPostamble:(NSString * _Nonnull)postamble withCompletionHandler:(void (^ _Nonnull)(SKTResult))completion;
/// get the device data source information
/// \param data source Id contains the data source ID for which the information would be retrieved
///
/// \param completion receiving the result and the device data source information if the result is successful
///
- (void)getDataSourceInfoFromId:(SKTCaptureDataSourceID)dataSourceId withCompletionHandler:(void (^ _Nonnull)(SKTResult, SKTCaptureDataSource * _Nullable))completion;
/// set the device data source information
/// \param dataSource data source to enable or disable
///
/// \param completion receiving the result of changing the device data source
///
- (void)setDataSourceInfo:(SKTCaptureDataSource * _Nonnull)dataSource withCompletionHandler:(void (^ _Nonnull)(SKTResult))completion;
/// set the device trigger
/// this operation can programmatically start a device read operation, or it can
/// disable the device trigger button until it gets re-enable again by using this
/// function too.
/// \param trigger contains the trigger command to apply
///
/// \param completion receiving the result of setting the trigger
///
- (void)setTrigger:(SKTCaptureTrigger)trigger withCompletionHandler:(void (^ _Nonnull)(SKTResult))completion;
/// set the decoded data confirmation
/// This function is required to acknowledge the decoded data that has been received
/// when the data confirmation mode has been set to SKTCaptureDataConfirmationModeApp
/// This function could also be called at any point of time if something needs to
/// be reported to the user. By example making the scanner beep or vibrate to get
/// the user to look at a screen.
/// note: Good AND Bad settings can not be used together.
/// \param led contains the led to light (None, Green, Red)
///
/// \param beep contains the beep to perform (None, Good, Bad)
///
/// \param rumble contains the rumble to perform (None, Good, Bad)
///
/// \param completion receiving the result of setting the decoded data confirmation
///
- (void)setDataConfirmationWithLed:(SKTCaptureDataConfirmationLed)led withBeep:(SKTCaptureDataConfirmationBeep)beep withRumble:(SKTCaptureDataConfirmationRumble)rumble withCompletionHandler:(void (^ _Nonnull)(SKTResult))completion;
/// set the device notifications
/// \param notifications select the notifications to receive
///
/// \param completion receiving the result of setting the notifications
///
- (void)setNotifications:(SKTCaptureNotifications)notifications withCompletionHandler:(void (^ _Nonnull)(SKTResult))completion;
/// set the SocketCam overlay view parameters mainly for the ViewFinder view
/// \param parameters dictionary containing the parameters for the ViewFinder
///
/// \param completion closure receiving the result of setting the Overlay View parameters
///
- (void)setSocketCamOverlayViewParameter:(NSDictionary<NSString *, id> * _Nonnull)parameters withCompletionHandler:(void (^ _Nonnull)(SKTResult))completion;
/// get the SocketCam overlay view parameters used mainly for the ViewFinder view
/// \param completion closure receiving the result and the overlay view parameters
///
- (void)getSocketCamOverlayViewParameterWithCompletionHandler:(void (^ _Nonnull)(SKTResult, NSDictionary<NSString *, id> * _Nullable))completion;
/// send a specific command to the device
/// These commands are specific to a device, therefore the device should first be identified
/// before sending such commands otherwise an unpredicable result could happen if they are
/// sent to a different device.
/// \param command an array of bytes that holds the specific command to send to the device
///
/// \param completion receiving the result and the device specific command response if the result is successful
///
- (void)getDeviceSpecificCommand:(NSData * _Nonnull)command withCompletionHandler:(void (^ _Nonnull)(SKTResult, NSData * _Nullable))completion;
/// Set a data format to the device
/// Examples:
/// ID-Only, TagType-and-ID, Data-Only, TagType-and-Data
- (void)setDataFormatWithDataFormat:(SKTCaptureDataFormat)dataFormat completion:(void (^ _Nonnull)(SKTResult))completion;
/// get a property using the Capture property object
/// Usually the get property sends a property without arguments but
/// the response in case of success contains a property response that
/// holds the eventual arguments of the property.
/// \param property reference to the property to set
///
/// \param completion receiving the result and the device specific command response if the result is successful
///
- (void)getProperty:(SKTCaptureProperty * _Nonnull)property withCompletionHandler:(void (^ _Nonnull)(SKTResult, SKTCaptureProperty * _Nullable))completion;
/// set a property using the Capture property object
/// Usually the set property does not return any property arguments,
/// only the result is interesting to check to know if the set property
/// has been successful.
/// \param property reference to the property to set
///
/// \param completion receiving the result and the device specific command response if the result is successful
///
- (void)setProperty:(SKTCaptureProperty * _Nonnull)property withCompletionHandler:(void (^ _Nonnull)(SKTResult, SKTCaptureProperty * _Nullable))completion;
@end




SWIFT_CLASS("_TtC10CaptureSDK26CaptureHelperDeviceManager")
@interface CaptureHelperDeviceManager : CaptureHelperDevice
- (void)startDiscoveryWithTimeout:(NSInteger)timeout withCompletionHandler:(void (^ _Nonnull)(SKTResult))completion;
- (void)setFavoriteDevices:(NSString * _Nonnull)favorites withCompletionHandler:(void (^ _Nonnull)(SKTResult))completion;
- (void)getFavoriteDevicesWithCompletionHandler:(void (^ _Nonnull)(SKTResult, NSString * _Nullable))completion;
- (void)getDeviceUniqueIdentifierFromDeviceGuid:(NSString * _Nonnull)deviceGuid withCompletionHandler:(void (^ _Nonnull)(SKTResult, NSString * _Nullable))completion;
@end


/// Capture Helper protocol to comply in order to receive the device manager discovery notifications
SWIFT_PROTOCOL("_TtP10CaptureSDK43CaptureHelperDeviceManagerDiscoveryDelegate_")
@protocol CaptureHelperDeviceManagerDiscoveryDelegate <CaptureHelperDelegate>
/// delegate called when a device manager discovered a device
/// \param device contains the device information, such as device type
///
/// \param deviceManager contains the device manager information from which the discovery was launched
///
- (void)didDiscoverDevice:(NSString * _Nonnull)device fromDeviceManager:(CaptureHelperDeviceManager * _Nonnull)deviceManager;
/// delegate called when a device manager ended the discovery
/// \param result contains the result of the device manager disconnecting from the host
///
/// \param deviceManager contains the device manager information from which the discovery ended
///
- (void)didEndDiscoveryWithResult:(SKTResult)result fromDeviceManager:(CaptureHelperDeviceManager * _Nonnull)deviceManager;
@end





/// Communication mode
typedef SWIFT_ENUM(uint8_t, CommMode, open) {
  CommModePlain = 0x00,
  CommModeMACed = 0x01,
  CommModeSecure = 0x03,
};

/// Key Index
typedef SWIFT_ENUM(uint8_t, KeyIndex, open) {
  KeyIndexUser = 0x00,
  KeyIndexAdmin = 0x01,
  KeyIndexNone = 0x02,
};


@class SCardReader;

/// Represents a channel
/// You can get this object with a call to <code>reader.cardConnect()</code>
/// author:
/// <a href="https://www.springcard.com">SpringCard</a>
/// copyright:
/// <a href="https://www.springcard.com">SpringCard</a>
/// <ul>
///   <li>
///     Version 1.0
///   </li>
/// </ul>
SWIFT_CLASS("_TtC10CaptureSDK12SCardChannel")
@interface SCardChannel : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull atrHexa;
/// Points to an <code>SCardReader</code> object
/// remark:
/// read-only
@property (nonatomic, readonly, strong) SCardReader * _Nonnull parent;
/// Was the channel unpowered after the reader went to sleep?
@property (nonatomic, readonly) BOOL isUnpowered;
/// Card’s ATR
/// remark:
/// read-only
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull atr;
@property (nonatomic, readonly, copy) NSString * _Nonnull friendlyName;
/// Transmit a C-APDU to the card, receive the R-APDU in response (in the callback)
/// \param command The C-APDU to send to the card
///
///
/// returns:
/// Nothing, answer is available in the <code>onTransmitDidResponse()</code> callback
- (void)transmitWithCommand:(NSArray<NSNumber *> * _Nonnull)command;
/// Disconnect from the card (close the communication channel + power down)
///
/// returns:
/// Nothing, answer is available in the <code>onCardDidDisconnect()</code> callback
- (void)cardDisconnect;
/// Connect to the card again (re-open an existing communication channel
///
/// returns:
/// Nothing, answer is available in the <code>onCardDidConnect()</code> callback
- (void)cardReconnect;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class SCardReaderList;

/// Represents a slot
/// You can get this object with a call to <code>SCardReaderList.getReader()</code>
/// remark:
/// This object implements the Equatable protocol
/// author:
/// <a href="https://www.springcard.com">SpringCard</a>
/// copyright:
/// <a href="https://www.springcard.com">SpringCard</a>
/// <ul>
///   <li>
///     Version 1.0
///   </li>
/// </ul>
SWIFT_CLASS("_TtC10CaptureSDK11SCardReader")
@interface SCardReader : NSObject
/// Contains the slot’s index
/// remark:
/// read-only
@property (nonatomic, readonly) NSInteger index;
/// Contains the slot’s name
/// remark:
/// read-only
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
/// Points to an <code>SCardReaderList</code> object
/// remark:
/// read-only
@property (nonatomic, readonly, strong) SCardReaderList * _Null_unspecified parent;
/// Is card powered (by the application) ?
/// remark:
/// read-only
@property (nonatomic, readonly) BOOL cardPowered;
/// Is a card present in the reader (slot) ?
/// remark:
/// read-only
@property (nonatomic, readonly) BOOL cardPresent;
/// Send a direct command to the device
/// \param command The command to send to the reader
///
///
/// returns:
/// Nothing, answer is available in the <code>onControlDidResponse()</code> callback
- (void)controlWithCommand:(NSArray<NSNumber *> * _Nonnull)command;
/// Connect to the card (power up + open a communication channel with the card)
///
/// returns:
/// Nothing, answer is available in the <code>onCardDidConnect()</code> callback
- (void)cardConnect;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSDate;
@class CBPeripheral;
@class CBCentralManager;
@protocol SCardReaderListDelegate;
@class SecureConnectionParameters;
@class CBService;
@class CBCharacteristic;
@class CBUUID;

/// Main class, instanciate a reader list, manage slots, enable sending APDUs in transmit and control mode, etc
/// author:
/// <a href="https://www.springcard.com">SpringCard</a>
/// copyright:
/// <a href="https://www.springcard.com">SpringCard</a>
/// <ul>
///   <li>
///     Version 1.0
///   </li>
/// </ul>
SWIFT_CLASS("_TtC10CaptureSDK15SCardReaderList")
@interface SCardReaderList : NSObject <CBCentralManagerDelegate, CBPeripheralDelegate>
/// Represent the vendor’s name
@property (nonatomic, copy) NSString * _Nonnull vendorName;
/// Product’s name
@property (nonatomic, copy) NSString * _Nonnull productName;
/// Device serial number, expressed in hex
@property (nonatomic, copy) NSString * _Nonnull serialNumber;
/// Device serial number of the BLE device
@property (nonatomic, copy) NSArray<NSNumber *> * _Nullable serialNumberRaw;
/// Firmware’s version
@property (nonatomic, copy) NSString * _Nonnull firmwareVersion;
/// Hardware version
@property (nonatomic, copy) NSString * _Nonnull hardwareVersion;
/// Software version
@property (nonatomic, copy) NSString * _Nonnull softwareVersion;
@property (nonatomic, copy) NSString * _Nonnull pnpId;
/// Battery level in percentage
@property (nonatomic) NSInteger batteryLevel;
/// Slots count (0 = device is not authentic)
@property (nonatomic) NSInteger slotCount;
/// Name of each slot, if names are equal to an empty string then there was an error
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull slots;
/// Transmit Power Level
@property (nonatomic) NSInteger powerLevel;
/// Battery Power State
@property (nonatomic) NSInteger powerState;
/// Is the reader in low power mode?
@property (nonatomic) BOOL isInLowPowerMode;
/// Value of the last slot status (of the last exchange)
@property (nonatomic, readonly) uint8_t slotStatus;
/// Value of the last slot error (of the last exchange)
@property (nonatomic, readonly) uint8_t slotError;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull libraryName;)
+ (NSString * _Nonnull)libraryName SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull LibrarySpecial;)
+ (NSString * _Nonnull)LibrarySpecial SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL libraryDebug;)
+ (BOOL)libraryDebug SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull libraryVersion;)
+ (NSString * _Nonnull)libraryVersion SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull libraryVersionMajor;)
+ (NSString * _Nonnull)libraryVersionMajor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull libraryVersionMinor;)
+ (NSString * _Nonnull)libraryVersionMinor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull LibraryVersionBuild;)
+ (NSString * _Nonnull)LibraryVersionBuild SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSDate * _Nonnull LibraryBuildDate;)
+ (NSDate * _Nonnull)LibraryBuildDate SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSDate * _Nonnull LibrarycompileDate;)
+ (NSDate * _Nonnull)LibrarycompileDate SWIFT_WARN_UNUSED_RESULT;
/// :nodoc:
- (nonnull instancetype)initWithDevice:(CBPeripheral * _Nonnull)device centralManager:(CBCentralManager * _Nonnull)centralManager delegate:(id <SCardReaderListDelegate> _Nullable)delegate secureConnectionParameters:(SecureConnectionParameters * _Nullable)secureConnectionParameters OBJC_DESIGNATED_INITIALIZER;
- (SCardReader * _Nullable)objectAtIndexedSubscript:(NSInteger)slot SWIFT_WARN_UNUSED_RESULT;
- (SCardReader * _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)slot SWIFT_WARN_UNUSED_RESULT;
/// :nodoc:
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didDiscoverServices:(NSError * _Nullable)error;
/// :nodoc:
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didDiscoverCharacteristicsForService:(CBService * _Nonnull)service error:(NSError * _Nullable)error;
/// :nodoc:
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didUpdateValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
/// :nodoc:
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didUpdateNotificationStateForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
/// :nodoc:
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didWriteValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
/// :nodoc:
- (void)centralManagerDidUpdateState:(CBCentralManager * _Nonnull)central;
/// :nodoc:
- (void)centralManager:(CBCentralManager * _Nonnull)central didDisconnectPeripheral:(CBPeripheral * _Nonnull)peripheral error:(NSError * _Nullable)error;
/// Send a direct command to the device
/// \param command The command to send to the reader
///
///
/// returns:
/// Nothing, answer is available in the <code>onControlDidResponse()</code> callback
- (void)controlWithCommand:(NSArray<NSNumber *> * _Nonnull)command;
/// Close connection with the product
/// \param keepBleActive if true then the Bluetooth connection remains active, when false the Bluetooth connection is also closed
///
- (void)closeWithKeepBleActive:(BOOL)keepBleActive;
/// Request for the creation of a PC/SC product <em>over BLE</em>
/// seealso:
/// <code>getAllAdvertisingServices()</code>
/// remark:
/// The instanciation of the CBCentralManager, the scan of BLE peripherals and the connection to the device must be done by the library’s client
/// \param peripheral The peripheral the application is connected to
///
/// \param centralManager The system Central Manager (must be a singleton)
///
/// \param delegate “pointer” to the class that implements the callbacks (usually “self”)
///
/// \param secureConnectionParameters Object of type <code>SecureConnectionParameters</code> used to pass secure communication parameters (optional)
///
///
/// returns:
/// As the code is asynchronous, the onReaderListDidCreate() callback of the delegate will be called in case of success or failure (i.e you need to verify the error parameter)
+ (void)createWithPeripheral:(CBPeripheral * _Nonnull)peripheral centralManager:(CBCentralManager * _Nonnull)centralManager delegate:(id <SCardReaderListDelegate> _Nonnull)delegate secureConnectionParameters:(SecureConnectionParameters * _Nullable)secureConnectionParameters;
/// Get the list of services UUID to filter scan
///
/// returns:
/// array of services UUIDs
+ (NSArray<CBUUID *> * _Nonnull)getAllAdvertisingServices SWIFT_WARN_UNUSED_RESULT;
/// Get the last error code
///
/// returns:
/// Int
- (NSInteger)lastError SWIFT_WARN_UNUSED_RESULT;
/// returns the last error message
///
/// returns:
/// a string describing the problem, can be a message from the system or a message specific to the SpringCard library
- (NSString * _Nonnull)lastErrorMessage SWIFT_WARN_UNUSED_RESULT;
/// Returns the connection status
///
/// returns:
/// true if there is a connection to a BLE device
- (BOOL)connected SWIFT_WARN_UNUSED_RESULT;
/// Is the connection valid?
///
/// returns:
/// Boolean
- (BOOL)valid SWIFT_WARN_UNUSED_RESULT;
/// Get a Reader objet from a slot’s name
/// \param slot name of the slot from the <code>slots</code> property
///
///
/// returns:
/// a <code>Reader</code> object or nil if the slot’s name is unknown
- (SCardReader * _Nullable)getReaderFromStringWithSlot:(NSString * _Nonnull)slot SWIFT_WARN_UNUSED_RESULT;
/// Get a Reader object from a slot’s index
/// \param slot index (0 based) of the slot from the <code>slots</code> property
///
///
/// returns:
/// a <code>Reader</code> object or nil if the index is out of bounds
- (SCardReader * _Nullable)getReaderFromIndexWithSlot:(NSInteger)slot SWIFT_WARN_UNUSED_RESULT;
/// Wake-up the reader, if it is in low power mode.
/// seealso:
/// <code>onReaderListState()</code>
- (void)wakeUp;
/// Ask the device to enter full power-down mode
/// remark:
/// Not all hardware support a full power-down mode. For devices without such capabilities, this instruction is equivalent to a warm reset.
- (void)shutdown;
/// Read device power state & battery level
///
/// returns:
/// Nothing, answer is available in the <code>onPowerInfo()</code> callback
- (void)getPowerInfo;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// All the protocols to implement in the client app
/// author:
/// <a href="https://www.springcard.com">SpringCard</a>
/// copyright:
/// <a href="https://www.springcard.com">SpringCard</a>
/// <ul>
///   <li>
///     Version 1.0
///   </li>
/// </ul>
SWIFT_PROTOCOL("_TtP10CaptureSDK23SCardReaderListDelegate_")
@protocol SCardReaderListDelegate <NSObject>
/// When the SCardReaderListe.create() methods finished its job, this method is called
/// remark:
/// In the callback, the first thing to do is to validate that the error parameter is not nil
/// \param readers in case of success an instance of an object of type <code>SCardReaderList</code>
///
/// \param error In case of problem this parameter is not nil and contains an error code and message
///
- (void)onReaderListDidCreateWithReaders:(SCardReaderList * _Nullable)readers error:(NSError * _Nullable)error;
/// When a deconnection from the current connected device is asked or when the device itself disconnect
/// \param readers Object of type <code>SCardReaderList</code>
///
/// \param error In case of problem this parameter is not nil and contains an error code and message
///
- (void)onReaderListDidCloseWithReaders:(SCardReaderList * _Nullable)readers error:(NSError * _Nullable)error;
/// When a response is received after a call to <code>SCardReaderList.control()</code>
/// \param readers Object of type <code>SCardReaderList</code>
///
/// \param response a byte array if everything went well or nil in cas of problem.
///
/// \param error In case of problem this parameter is not nil and contains an error code and message
///
- (void)onControlDidResponseWithReaders:(SCardReaderList * _Nullable)readers response:(NSArray<NSNumber *> * _Nullable)response error:(NSError * _Nullable)error;
/// When a card is inserted into, or removed from an active reader
/// \param reader Object of type <code>SCardReader</code>
///
/// \param present Is the card present?
///
/// \param powered Is the card powered?
///
/// \param error In case of problem this parameter is not nil and contains an error code and message
///
- (void)onReaderStatusWithReader:(SCardReader * _Nullable)reader present:(BOOL)present powered:(BOOL)powered error:(NSError * _Nullable)error;
/// Invoked when the device is going to sleep or waking up
/// \param readers Object of type <code>SCardReaderList</code>
///
/// \param isInLowPowerMode true if the product is going to low power mode, false if it is waking-up
///
- (void)onReaderListStateWithReaders:(SCardReaderList * _Nonnull)readers isInLowPowerMode:(BOOL)isInLowPowerMode;
/// When a R-APDU is received after a call to <code>SCardChannel.transmit()</code>
/// \param channel The channel that sent the C-APUD (object of type <code>SCardChannel</code>), can be nil in case of error
///
/// \param response a byte array if everything went well or nil in case of problem
///
/// \param error In case of problem this parameter is not nil and contains an error code and message
///
- (void)onTransmitDidResponseWithChannel:(SCardChannel * _Nullable)channel response:(NSArray<NSNumber *> * _Nullable)response error:(NSError * _Nullable)error;
/// Used to give the result of a <code>SCardReader.cardConnect()</code>
/// \param channel Object of type <code>SCardChannel</code> or nil in case of problem
///
/// \param error In case of problem this parameter is not nil and contains an error code and message
///
- (void)onCardDidConnectWithChannel:(SCardChannel * _Nullable)channel error:(NSError * _Nullable)error;
/// Callback used for giving the result of a channel.cardDisconnect()
/// \param channel Object of type <code>SCardChannel</code> or nil in case of problem
///
/// \param error In case of problem this parameter is not nil and contains an error code and message
///
- (void)onCardDidDisconnectWithChannel:(SCardChannel * _Nullable)channel error:(NSError * _Nullable)error;
/// Read device’s power state & battery level
/// \param powerState See https://docs.springcard.com/books/SpringCore/Host_interfaces/BLE/Standard_Services#page_Device-s-power-capabilities-and-states
///
/// \param batteryLevel 0-100%
///
- (void)onPowerInfoWithPowerState:(NSInteger)powerState batteryLevel:(NSInteger)batteryLevel error:(NSError * _Nullable)error;
@end


/// :nodoc:
SWIFT_CLASS("_TtC10CaptureSDK24SCardReaderList_D600_BLE")
@interface SCardReaderList_D600_BLE : SCardReaderList
- (nonnull instancetype)initWithDevice:(CBPeripheral * _Nonnull)device centralManager:(CBCentralManager * _Nonnull)centralManager delegate:(id <SCardReaderListDelegate> _Nullable)delegate secureConnectionParameters:(SecureConnectionParameters * _Nullable)secureConnectionParameters OBJC_DESIGNATED_INITIALIZER;
@end


/// :nodoc:
SWIFT_CLASS("_TtC10CaptureSDK31SCardReaderList_PUCK_BLE_Bonded")
@interface SCardReaderList_PUCK_BLE_Bonded : SCardReaderList
- (nonnull instancetype)initWithDevice:(CBPeripheral * _Nonnull)device centralManager:(CBCentralManager * _Nonnull)centralManager delegate:(id <SCardReaderListDelegate> _Nullable)delegate secureConnectionParameters:(SecureConnectionParameters * _Nullable)secureConnectionParameters OBJC_DESIGNATED_INITIALIZER;
@end


/// :nodoc:
SWIFT_CLASS("_TtC10CaptureSDK33SCardReaderList_PUCK_BLE_Unbonded")
@interface SCardReaderList_PUCK_BLE_Unbonded : SCardReaderList
- (BOOL)isBoundedDevice SWIFT_WARN_UNUSED_RESULT;
- (void)setSpecificDeviceServices;
- (nonnull instancetype)initWithDevice:(CBPeripheral * _Nonnull)device centralManager:(CBCentralManager * _Nonnull)centralManager delegate:(id <SCardReaderListDelegate> _Nullable)delegate secureConnectionParameters:(SecureConnectionParameters * _Nullable)secureConnectionParameters OBJC_DESIGNATED_INITIALIZER;
@end


/// Parameters used to describe a secure connection
SWIFT_CLASS("_TtC10CaptureSDK26SecureConnectionParameters")
@interface SecureConnectionParameters : NSObject
- (nonnull instancetype)initWithAuthMode:(enum AuthenticationMode)authMode keyIndex:(enum KeyIndex)keyIndex keyValue:(NSArray<NSNumber *> * _Nonnull)keyValue commMode:(enum CommMode)commMode debugSecureCommunication:(BOOL)debugSecureCommunication OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10CaptureSDK9SktLogger")
@interface SktLogger : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@class UIViewController;

SWIFT_CLASS("_TtC10CaptureSDK24SocketCamControllerSwift")
@interface SocketCamControllerSwift : NSObject
@property (nonatomic, readonly) BOOL isBeepFilePresent;
@property (nonatomic, strong) UIViewController * _Nullable parent;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (BOOL)startScanWith:(BOOL)continousScan SWIFT_WARN_UNUSED_RESULT;
- (BOOL)stopScan SWIFT_WARN_UNUSED_RESULT;
- (void)turnFlashWith:(BOOL)turnOn;
- (void)setBeepWith:(BOOL)beepOn;
- (void)setVibrateWith:(BOOL)vibrateOn;
- (void)updateDataSourceStatusWith:(NSInteger)status with:(NSInteger)dataSourceIndex;
- (NSInteger)getDataSourcesCount SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getDataSourceTypeFrom:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getDataSourceIndexFrom:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getDataSourceNameFrom:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getDataSourceDescriptionFrom:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)retrieveDataSourceIdFrom:(NSString * _Nonnull)type SWIFT_WARN_UNUSED_RESULT;
@end


/// Builtin SocketCam delegate
/// This delegate is used when we receive notification from
/// iOS SocketCam
SWIFT_PROTOCOL("_TtP10CaptureSDK17SocketCamDelegate_")
@protocol SocketCamDelegate
- (void)didRead:(NSString * _Nonnull)barcode ofType:(NSString * _Nonnull)type;
- (void)didNotRead;
- (NSArray * _Nonnull)buildDataSourceEnabledList SWIFT_WARN_UNUSED_RESULT;
@end


@interface SocketCamControllerSwift (SWIFT_EXTENSION(CaptureSDK)) <SocketCamDelegate>
- (void)didRead:(NSString * _Nonnull)barcode ofType:(NSString * _Nonnull)type;
- (void)didNotRead;
- (NSArray * _Nonnull)buildDataSourceEnabledList SWIFT_WARN_UNUSED_RESULT;
@end


#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif
